
# EMBEDDED SERVER CONFIGURATION
server:
    port: ${port:8741}
    error.whitelabel.enabled: false

# EUREKA
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
# LOGGING
#logging.level.org.springframework.security: DEBUG

sidecar:
  port: 3000
  home-page-uri: http://localhost:${sidecar.port}/
  health-uri: http://localhost:${sidecar.port}/health

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

---

spring:
  profiles: docker

# EUREKA
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8081/eureka/

---

spring:
  profiles: standalone

# EUREKA
eureka:
  instance:
    hostname: localhost
    port: 8081
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
