# EMBEDDED SERVER CONFIGURATION
server:
    port: ${port:8989}
    error.whitelabel.enabled: false

turbine:
  appConfig: web,user-api-service,travel-history-api-service
  aggregator:
    clusterConfig: WEB,USER-API-SERVICE,TRAVEL-HISTORY-API-SERVICE

# EUREKA
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
# LOGGING
#logging.level.org.springframework.security: DEBUG

---

spring:
  profiles: docker

# EUREKA
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8081/eureka/

---

spring:
  profiles: standalone

# EUREKA
eureka:
  instance:
    hostname: localhost
    port: 8081
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
